### ISSUE TITLE
Cannot install ag-grid-angular

### ISSUE THREAD

**Issue by deanchalk** [ceolter/ag-grid-angular#155] opened 2017-06-24 16:55 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
error running npm installation for ag-grid-angular

**Expected behavior**
the npm installer works

**Minimal reproduction of the problem with instructions**
run npm i ag-grid-angular

**What is the motivation / use case for changing the behavior?**
I just wanna install it

**Please tell us about your environment:**
Window 10, Angular 4, node 6.10.3, npm 3.10.10 - running with admin rights

* **ag-grid-angular version:** 2.0.X
4.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X
yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
not browser issue

Here is the terminal output when trying to install ag-grid-angular:

 WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Projects\SpecMatcher\node_modules\.staging\ag-grid-angular-f7f641b7
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\SpecMatcher\node_modules\.staging\ag-grid-angular-f7f641b7' -> 'C:\Projects\SpecMatcher\node_modules\ag-grid-angular'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\SpecMatcher\node_modules\.staging\ag-grid-angular-f7f641b7' -> 'C:\Projects\SpecMatcher\node_modules\ag-grid-angular'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Projects\SpecMatcher\node_modules\.staging\ag-grid-angular-f7f641b7' -> 'C:\Projects\SpecMatcher\node_modules\ag-grid-angular'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\SpecMatcher\node_modules\.staging\ag-grid-angular-f7f641b7' -> 'C:\Projects\SpecMatcher\node_modules\ag-grid-angular'
npm ERR!     at Error (native) parent: 'spec-matcher' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\SpecMatcher\npm-debug.log

the logfile mentioned above does not exist

I cannot install this package with npm

**Comment by seanlandsman** [comment] 2017-06-26 05:28
Hi

I've just tried this both on a Mac and on a Windows 10 PC - it installs fine on both (and you shouldn't need to be an admin to install it either)

npm 3.10.10
node v6.11.0

It appears to be failing with "operation not permitted, rename" - I'm not sure whats causing this, but it isnt part of the standard install

**Comment by seanlandsman** [comment] 2017-07-06 09:19
Closing as cannot reproduce

**Closed by seanlandsman** 2017-07-06 09:19 UTC
Labels: need repro

**Comment by ssashok10** [comment] 2017-09-13 13:34
I am getting the similar error when I tried to install with Angular 4.2.4. My node version is 8.4.0 and npm version is 5.4.1. The installation is conflicting something with "fsevents"...Here is the error, 

npm ERR! path I:\git\AngularAppSample\node_modules\
fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSample\node_modules\fsevents\node_modules\abbrev\package.j
son'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'I:\git\AngularAppSamplenode_modules\fsevents\node_modules\abbrev\packag
e.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'I:\\git\\AngularAppSample\\node_modules\\fsevents\\node_modul
es\\abbrev\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'I:\\git\\AngularAppSample\\nod
e_modules\\fsevents\\node_modules\\abbrev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sath\AppData\Roaming\npm-cache\_logs\2017-09-12T21_37_0
9_061Z-debug.log

**Comment by kbommalingaiah** [comment] 2019-07-26 13:00
cannot install ag-grid-angular 
my node is 10  and npm is 6
