### ISSUE TITLE
ag-grid-ng2 7.2.2 - cannot use directives within CellRendererComponent

### ISSUE THREAD

**Issue by shware100** [ceolter/ag-grid-angular#130] opened 2017-02-17 20:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Directives do not seem to be loading when declared on a custom component used from a colDef via CellRendererFramework.  The app compiles, but the directive's constructor is never hit.

**Expected behavior**

Directives should work as usual within Angular2 components which are rendered as part of the CellRendererFramework.

**Minimal reproduction of the problem with instructions**

Create a basic Angular2 directive - like one to set text color

Create a basic CellRendererComponent which implements AgRendererComponent and reference it in a grid's colDef.

Reference the directive in the cell renderer's template.

The directive is never loaded.

**What is the motivation / use case for changing the behavior?**

Angular2 directives are a key part of the Angular2 framework.  Not having the ability to implement directives within custom renderer components hinders ability to reuse existing code.

**Please tell us about your environment:**

Windows 7, VSCode, npm, webpack, webpack dev server

* **ag-grid-ng2 version: 7.2.2

Using current npm build.

* **ag-Grid/ag-Grid-Enterprise version:** N/A

* **Angular version:** 2.3.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Only tested on Chrome.  Other browsers not available at work.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

Thanks for an awesome piece of software!

**Comment by seanlandsman** [comment] 2017-02-20 14:03
Hi

I am unable to reproduce this - I have the following directive:

`import {Directive, ElementRef} from "@angular/core";

@Directive({selector: '[myHighlight]'})
export class ColourDirective{
    constructor(el: ElementRef) {
        el.nativeElement.style.backgroundColor = 'yellow';
    }
}`

And the following component:

`@Component({
    selector: 'star',
    template: `
        <span myHighlight>Yay! Should be yellow.</span>
    `
})
export class StarComponent implements AgRendererComponent {
    private params: any;
    ...rest of the component - doenst do anything for this example
`

And it renderers as expected.

Do you have a plunker I can take a look at?

**Comment by shware100** [comment] 2017-02-22 22:15
Hi,

Thanks very much for your research and response.  With this info I was able to get a basic directive working in a single module app but not in my larger project.

I'll continue to hack to see if I can determine cause and provide more info if able.

Thanks again.

**Comment by shware100** [comment] 2017-02-23 14:31
Just a bit more research.  Seems if the directives are declared in a module separate from the module declaring the AgGrid.withComponents[...], the directives within renderer templates do not get instantiated.  

It's entirely possible our DI is whacked but this problem only started occurring with v7.2.2.  Prior versions using the cellRendererFramework / moduleImports worked fine with our module structures.

Will try and carve out a small app and try to reproduce further.

Thanks again.

**Comment by seanlandsman** [comment] 2017-02-23 15:00
Well thats interesting. Prior to 7 we created both modules and components on the fly, which allowed us plenty of flexibility, but at the expense of AOT.

As AOT is such a big part of Angular, we had to switch approaches, but that said it should still allow directives & components to play nice.

I'll wait for your example - once I have it I'm sure we'll be able to solve this problem

thanks

**Comment by seanlandsman** [comment] 2017-07-10 08:44
Closing as cannot reproduce

**Closed by seanlandsman** 2017-07-10 08:44 UTC
Labels: need repro

**Comment by MalleswaraoBandi** [comment] 2019-06-14 11:48
Can we use directives from column defs for a field without creating a child component and template.
